### ISSUE TITLE
import { style as tw } from 'twrnc'; Doesn't work

### ISSUE THREAD

**Issue by AndreiOvercode** [jaredh159/tailwind-react-native-classnames#253]
<img width="954" alt="image" src="https://github.com/jaredh159/tailwind-react-native-classnames/assets/138531148/8fa197dd-9119-4447-b56e-0a8cc774558e">

**Comment by jaredh159** [comment]
yeah, sorry about that, thanks for letting me know. fixed in `v3.6.5`

**Comment by AndreiOvercode** [comment]
@jaredh159 Sorry, but it still not working in v3.6.5

<img width="274" alt="image" src="https://github.com/jaredh159/tailwind-react-native-classnames/assets/138531148/4a840069-8526-4718-b007-a6c55e0a6745">

<img width="181" alt="image" src="https://github.com/jaredh159/tailwind-react-native-classnames/assets/138531148/0d3e86b8-75b3-4960-b52e-1c909494c4ac">

**Comment by jaredh159** [comment]
can you try blowing away your node_modules and re-installing?  i think it should be working, i export the `style` function explicitly, and tested it...

**Comment by AndreiOvercode** [comment]
> can you try blowing away your node_modules and re-installing? i think it should be working, i export the `style` function explicitly, and tested it...

Yes, thanks

After reinstalling node_modules everything works

**Comment by jaredh159** [comment]
glad to hear it 👍
